PYTHON3_APSCHEDULER_VERSION = 3.9.1
PYTHON3_APSCHEDULER_SITE = https://files.pythonhosted.org/packages/3a/7c/f21a6fb73810191d16162f3fce325ff2a62673f63223c390bea48741ea00
PYTHON3_APSCHEDULER_SOURCE = APScheduler-$(PYTHON3_APSCHEDULER_VERSION).tar.gz
PYTHON3_APSCHEDULER_LICENSE = MIT
PYTHON3_APSCHEDULER_LICENSE_FILES = LICENSE.txt
PYTHON3_APSCHEDULER_SETUP_TYPE = setuptools
PYTHON3_APSCHEDULER_DEPENDENCIES = python3 python-pip python-setuptools python3-tzlocal python-pytz
#HOST_PYTHON3_APSCHEDULER_DEPENDENCIES = host-python3
#HOST_PYTHON3_APSCHEDULER_NEEDS_HOST_PYTHON = python3

$(eval $(python-package))
#$(eval $(host-python-package))
