PYTHON3_TZLOCAL_VERSION = 4.2
PYTHON3_TZLOCAL_SITE = https://github.com/regebro/tzlocal.git
PYTHON3_TZLOCAL_SITE_METHOD = git
PYTHON3_TZLOCAL_LICENSE = MIT
PYTHON3_TZLOCAL_LICENSE_FILES = LICENSE.txt
PYTHON3_TZLOCAL_SETUP_TYPE = setuptools
PYTHON3_TZLOCAL_DEPENDENCIES = python3 python-pytz
#HOST_PYTHON3_TZLOCAL_DEPENDENCIES = host-python3
#HOST_PYTHON3_TZLOCAL_NEEDS_HOST_PYTHON = python3

$(eval $(python-package))
#$(eval $(host-python-package))
